In [123]:
# PLEASE NOTE: we have added comments where ever possible also we have included a short summary of how we found out our final
# model later on.

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
 
payment_history_data= pd.read_csv(r'D:\cassandra\payment_history_data.csv') #read data
train_data= pd.read_csv(r'D:\cassandra\train_data.csv')
print(payment_history_data.shape)
print(train_data.shape)
payment_history_data.head()

(8250, 12)
(715, 14)


id  Late_2  Late_1  Late_3  days_late_Sum  normal_payment  p_code  \
0   1       0       0       0              0               1      10   
1   1       1       0       0              1              31      10   
2   1       0       0       0              0              19      10   
3   1       0       0      35          31500               0      10   
4   1       0       0       0              0              26      10   

    p_limit  last_update  curr_remaining   max_bal  recent_payment_activity  
0   55000.0      41900.0             0.0    2068.0                  41800.0  
1  550000.0      41500.0        326684.4  609683.0                  42400.0  
2       NaN      40700.0         31677.6  204037.0                  42400.0  
3   12100.0      39800.0         12142.8   10619.0                  40000.0  
4  660000.0      39200.0        252998.4  775030.0                  42400.0

In [124]:
payment_history_data.drop('p_limit',axis=1,inplace=True) #remove column p_limit
print(payment_history_data.shape)
print(train_data.shape)
payment_history_data.head()

(8250, 11)
(715, 14)


id  Late_2  Late_1  Late_3  days_late_Sum  normal_payment  p_code  \
0   1       0       0       0              0               1      10   
1   1       1       0       0              1              31      10   
2   1       0       0       0              0              19      10   
3   1       0       0      35          31500               0      10   
4   1       0       0       0              0              26      10   

   last_update  curr_remaining   max_bal  recent_payment_activity  
0      41900.0             0.0    2068.0                  41800.0  
1      41500.0        326684.4  609683.0                  42400.0  
2      40700.0         31677.6  204037.0                  42400.0  
3      39800.0         12142.8   10619.0                  40000.0  
4      39200.0        252998.4  775030.0                  42400.0

In [125]:
payment_history_data.drop('recent_payment_activity',axis=1,inplace=True) #remove col recent_pay..
print(payment_history_data.shape)
print(train_data.shape)
payment_history_data.head()

(8250, 10)
(715, 14)


id  Late_2  Late_1  Late_3  days_late_Sum  normal_payment  p_code  \
0   1       0       0       0              0               1      10   
1   1       1       0       0              1              31      10   
2   1       0       0       0              0              19      10   
3   1       0       0      35          31500               0      10   
4   1       0       0       0              0              26      10   

   last_update  curr_remaining   max_bal  
0      41900.0             0.0    2068.0  
1      41500.0        326684.4  609683.0  
2      40700.0         31677.6  204037.0  
3      39800.0         12142.8   10619.0  
4      39200.0        252998.4  775030.0

In [126]:
payment_history_data = payment_history_data.dropna(how='any',axis=0)  #remove rows with null values 

#mean=train_data['Beta'].mean() #calculate mean of Beta column
train_data['Beta'].fillna(value=train_data['Beta'].mean(), inplace=True)

train_data = train_data.dropna(how='any',axis=0)

print(payment_history_data.shape)
print(train_data.shape)
payment_history_data.head()

(7829, 10)
(715, 14)


id  Late_2  Late_1  Late_3  days_late_Sum  normal_payment  p_code  \
0   1       0       0       0              0               1      10   
1   1       1       0       0              1              31      10   
2   1       0       0       0              0              19      10   
3   1       0       0      35          31500               0      10   
4   1       0       0       0              0              26      10   

   last_update  curr_remaining   max_bal  
0      41900.0             0.0    2068.0  
1      41500.0        326684.4  609683.0  
2      40700.0         31677.6  204037.0  
3      39800.0         12142.8   10619.0  
4      39200.0        252998.4  775030.0

In [127]:
grouped=payment_history_data.groupby('id').agg([np.average]) #group is data that we need, take average of same id 
print(payment_history_data.shape) 
print(train_data.shape)
payment_history_data.head()

(7829, 10)
(715, 14)


id  Late_2  Late_1  Late_3  days_late_Sum  normal_payment  p_code  \
0   1       0       0       0              0               1      10   
1   1       1       0       0              1              31      10   
2   1       0       0       0              0              19      10   
3   1       0       0      35          31500               0      10   
4   1       0       0       0              0              26      10   

   last_update  curr_remaining   max_bal  
0      41900.0             0.0    2068.0  
1      41500.0        326684.4  609683.0  
2      40700.0         31677.6  204037.0  
3      39800.0         12142.8   10619.0  
4      39200.0        252998.4  775030.0

In [128]:
grouped.head()

Late_2    Late_1    Late_3 days_late_Sum normal_payment     p_code  \
        average   average   average       average        average    average   
id                                                                            
1      0.214286  0.142857  2.714286   2291.285714      15.928571   8.785714   
1114   0.000000  0.000000  0.000000      0.000000      16.714286  14.000000   
12615  0.272727  0.000000  0.000000      1.090909      22.363636   6.090909   
40811  0.000000  0.000000  0.000000      0.000000      17.000000   9.000000   
65668  0.000000  0.000000  0.000000      0.000000      14.000000  10.000000   

        last_update curr_remaining        max_bal  
            average        average        average  
id                                                 
1      38835.714286   53049.085714  246583.714286  
1114   37500.000000    2277.771429  196649.285714  
12615  40981.818182  117455.127273  238270.000000  
40811  41300.000000   39890.400000   78500.000000  
65668  41875.000000    1261.200000   12787.750000

In [129]:
grouped.shape

(1125, 9)

In [130]:
grouped_copy=grouped.copy() #copying grouped just in case

In [131]:
yplusx = pd.merge(grouped, train_data, on='id', how='inner') #merge both data to form final dataset
yplusx.drop('id',axis=1,inplace=True)

C:\Users\Aditya\Anaconda3\lib\site-packages\pandas\core\reshape\merge.py:617: UserWarning: merging between different levels can give an unintended result (2 levels on the left, 1 on the right)
  warnings.warn(msg, UserWarning)


In [132]:
yplusx.head()

(Late_2, average)  (Late_1, average)  (Late_3, average)  \
0                0.0                0.0                0.0   
1                0.0                0.0                0.0   
2                0.0                0.5                6.5   
3                0.0                0.0                0.0   
4                0.2                0.1                4.3   

   (days_late_Sum, average)  (normal_payment, average)  (p_code, average)  \
0                       0.0                  16.714286          14.000000   
1                       0.0                  15.785714           6.928571   
2                    2976.5                   8.500000           8.750000   
3                       0.0                  22.500000          10.000000   
4                    3349.7                  10.900000           8.500000   

   (last_update, average)  (curr_remaining, average)  (max_bal, average)  \
0                 37500.0                2277.771429       196649.285714   
1                 39700.0              132427.200000       235465.142857   
2                 40250.0               40112.400000        91298.000000   
3                 41600.0                8752.800000        34626.000000   
4                 39820.0               49843.440000        60931.800000   

   label  ...  Gamma    Delta  Epsilon  Zeta  Eta  Theta  Iota   Kappa  \
0      0  ...      1  1200000        2     5   -1     64     5  361026   
1      0  ...      3   325000        2    15    5    110     5   60033   
2      1  ...      3    77000        2    15    5    109     5  151300   
3      0  ...      3   130000        2    15    5     85     5   60047   
4      1  ...      2    90000        2    15    5     92     5   72014   

       Lambda   omikron  
0    1.000000  0.015625  
1  316.227766  0.027273  
2  244.948974  0.027523  
3  212.132034  0.035294  
4    1.000000  0.021739  

[5 rows x 22 columns]

In [133]:
yplusx.shape

(715, 22)

In [134]:
yplusx=yplusx.sample(frac=1) #shuffle the entire data
yplusx.shape

(715, 22)

In [135]:
val=yplusx[0:200] #split data into validation and train set
train=yplusx[200:]
print(val.shape)
print(train.shape)

(200, 22)
(515, 22)


In [136]:
val.head()

(Late_2, average)  (Late_1, average)  (Late_3, average)  \
403           0.117647                0.0                0.0   
65            1.500000                1.0                1.0   
418           0.000000                0.0                0.0   
51            0.000000                0.0                0.0   
188           0.000000                0.0                0.0   

     (days_late_Sum, average)  (normal_payment, average)  (p_code, average)  \
403                  1.294118                  25.117647           9.176471   
65                 226.500000                  16.500000          10.000000   
418                  0.000000                  21.571429           6.285714   
51                   0.000000                  12.000000          10.000000   
188                  0.000000                  16.352941           6.764706   

     (last_update, average)  (curr_remaining, average)  (max_bal, average)  \
403            39217.647059              102439.552941       121409.058824   
65             41700.000000               25982.400000        43324.500000   
418            40014.285714              104011.028571       507583.571429   
51             41950.000000               34134.000000        32451.500000   
188            40700.000000               62427.458824       304671.823529   

     label  ...  Gamma   Delta  Epsilon  Zeta  Eta  Theta  Iota   Kappa  \
403      0  ...      1   92000        2    11   -1    105     4  591003   
65       0  ...      3  108000        2    11    5    110     4  510068   
418      0  ...      1  150000        2    12   -1    110     5  350012   
51       1  ...      3   72000        2    11    5     85     5   60069   
188      0  ...      1  150000        2     8    5    110     5   60029   

         Lambda   omikron  
403  167.332005  0.009524  
65   248.997992  0.027273  
418    1.000000  0.009091  
51     1.000000  0.035294  
188  316.227766  0.009091  

[5 rows x 22 columns]

In [137]:
print(val.shape)
print(train.shape)

(200, 22)
(515, 22)


In [138]:
y_val=val['label']
x_val=val.loc[:, val.columns != 'label']
y_train=train['label']
x_train=train.loc[:, train.columns != 'label']

In [139]:
print(y_val.shape)
print(x_val.shape)
print(y_train.shape)
print(x_train.shape)

(200,)
(200, 21)
(515,)
(515, 21)


In [140]:
def normalize(df):
    result = df.copy()
    for feature_name in df.columns:
        max_value = df[feature_name].max()
        min_value = df[feature_name].min()
        result[feature_name] = (df[feature_name] - min_value) / (max_value - min_value)
    return result

x_train=normalize(x_train)
x_val=normalize(x_val)

In [141]:
x_val.head()

(Late_2, average)  (Late_1, average)  (Late_3, average)  \
403           0.033613           0.000000           0.000000   
65            0.428571           0.294118           0.076923   
418           0.000000           0.000000           0.000000   
51            0.000000           0.000000           0.000000   
188           0.000000           0.000000           0.000000   

     (days_late_Sum, average)  (normal_payment, average)  (p_code, average)  \
403                  0.000160                   0.683038           0.531590   
65                   0.027946                   0.432039           0.592593   
418                  0.000000                   0.579750           0.317460   
51                   0.000000                   0.300971           0.592593   
188                  0.000000                   0.427756           0.352941   

     (last_update, average)  (curr_remaining, average)  (max_bal, average)  \
403                0.168357                   0.114497            0.060762   
65                 0.810345                   0.029057            0.020887   
418                0.374384                   0.116253            0.257969   
51                 0.875000                   0.038167            0.015334   
188                0.551724                   0.069784            0.154348   

     Alpha  ...  Gamma     Delta  Epsilon      Zeta       Eta     Theta  Iota  \
403    1.0  ...    0.0  0.131915      1.0  0.636364  0.000000  0.803922  0.75   
65     1.0  ...    1.0  0.165957      1.0  0.636364  0.545455  0.901961  0.75   
418    1.0  ...    0.0  0.255319      1.0  0.727273  0.000000  0.901961  1.00   
51     1.0  ...    1.0  0.089362      1.0  0.636364  0.545455  0.411765  1.00   
188    0.5  ...    0.0  0.255319      1.0  0.363636  0.545455  0.901961  1.00   

        Kappa    Lambda   omikron  
403  1.000000  0.462605  0.017732  
65   0.847581  0.689736  0.484496  
418  0.546158  0.000000  0.006347  
51   0.000128  0.000000  0.695444  
188  0.000053  0.876716  0.006347  

[5 rows x 21 columns]

In [142]:

from sklearn.datasets import make_regression
from sklearn.model_selection import train_test_split
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import f_regression
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error
from sklearn.feature_selection import mutual_info_regression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import roc_auc_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix,accuracy_score
from sklearn.datasets import make_regression

# feature selection
def select_features(x_train, y_train, x_val, i):
    # configure to select a subset of features
    fs = SelectKBest(score_func=mutual_info_regression, k=i)
    # learn relationship from training data
    fs.fit(x_train, y_train)
    # transform train input data
    x_train_fs = fs.transform(x_train)
    # transform test input data
    x_val_fs = fs.transform(x_val)
    return x_train_fs, x_val_fs, fs

for i in range(1,22) :
    x_train_fs, x_val_fs, fs = select_features(x_train, y_train, x_val, i)

# logmodel = LogisticRegression()
# logmodel.fit(x_train_fs, y_train)
#     logmodel = SVC(kernel='linear', 
#     class_weight='balanced', # penalize
#     probability=True)
    logmodel = RandomForestClassifier()
 
    logmodel.fit(x_train_fs, y_train)

    #for i in range(len(fs.scores_)):
     #   print('Feature %d: %f' % (i, fs.scores_[i]))
     # plot the scores
    #pyplot.bar([i for i in range(len(fs.scores_))], fs.scores_)
    #pyplot.show()

    predictions = logmodel.predict(x_val_fs)
    print( roc_auc_score(y_val, predictions) )
    print(classification_report(y_val, predictions))
    print(confusion_matrix(y_val, predictions))
    print(accuracy_score(y_val, predictions))
    

C:\Users\Aditya\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Aditya\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


0.5190528034839412
              precision    recall  f1-score   support

           0       0.84      0.86      0.85       167
           1       0.20      0.18      0.19        33

    accuracy                           0.74       200
   macro avg       0.52      0.52      0.52       200
weighted avg       0.74      0.74      0.74       200

[[143  24]
 [ 27   6]]
0.745
0.47904191616766467
              precision    recall  f1-score   support

           0       0.83      0.96      0.89       167
           1       0.00      0.00      0.00        33

    accuracy                           0.80       200
   macro avg       0.41      0.48      0.44       200
weighted avg       0.69      0.80      0.74       200

[[160   7]
 [ 33   0]]
0.8


C:\Users\Aditya\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


0.47904191616766467
              precision    recall  f1-score   support

           0       0.83      0.96      0.89       167
           1       0.00      0.00      0.00        33

    accuracy                           0.80       200
   macro avg       0.41      0.48      0.44       200
weighted avg       0.69      0.80      0.74       200

[[160   7]
 [ 33   0]]
0.8


C:\Users\Aditya\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


0.49174378515695877
              precision    recall  f1-score   support

           0       0.83      0.86      0.85       167
           1       0.15      0.12      0.13        33

    accuracy                           0.74       200
   macro avg       0.49      0.49      0.49       200
weighted avg       0.72      0.74      0.73       200

[[144  23]
 [ 29   4]]
0.74


C:\Users\Aditya\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Aditya\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


0.4943748865904554
              precision    recall  f1-score   support

           0       0.83      0.93      0.88       167
           1       0.14      0.06      0.09        33

    accuracy                           0.79       200
   macro avg       0.49      0.49      0.48       200
weighted avg       0.72      0.79      0.75       200

[[155  12]
 [ 31   2]]
0.785
0.5366539647976774
              precision    recall  f1-score   support

           0       0.85      0.95      0.90       167
           1       0.33      0.12      0.18        33

    accuracy                           0.81       200
   macro avg       0.59      0.54      0.54       200
weighted avg       0.76      0.81      0.78       200

[[159   8]
 [ 29   4]]
0.815


C:\Users\Aditya\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Aditya\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


0.49455634186173103
              precision    recall  f1-score   support

           0       0.83      0.90      0.86       167
           1       0.15      0.09      0.11        33

    accuracy                           0.77       200
   macro avg       0.49      0.49      0.49       200
weighted avg       0.72      0.77      0.74       200

[[150  17]
 [ 30   3]]
0.765
0.5153329704227907
              precision    recall  f1-score   support

           0       0.84      0.97      0.90       167
           1       0.29      0.06      0.10        33

    accuracy                           0.82       200
   macro avg       0.56      0.52      0.50       200
weighted avg       0.75      0.82      0.77       200

[[162   5]
 [ 31   2]]
0.82


C:\Users\Aditya\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Aditya\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


0.5336599528216294
              precision    recall  f1-score   support

           0       0.84      0.95      0.89       167
           1       0.31      0.12      0.17        33

    accuracy                           0.81       200
   macro avg       0.58      0.53      0.53       200
weighted avg       0.76      0.81      0.77       200

[[158   9]
 [ 29   4]]
0.81
0.5033569225185991
              precision    recall  f1-score   support

           0       0.84      0.95      0.89       167
           1       0.18      0.06      0.09        33

    accuracy                           0.80       200
   macro avg       0.51      0.50      0.49       200
weighted avg       0.73      0.80      0.76       200

[[158   9]
 [ 31   2]]
0.8


C:\Users\Aditya\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Aditya\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


0.5851025222282707
              precision    recall  f1-score   support

           0       0.86      0.96      0.91       167
           1       0.50      0.21      0.30        33

    accuracy                           0.83       200
   macro avg       0.68      0.59      0.60       200
weighted avg       0.80      0.83      0.81       200

[[160   7]
 [ 26   7]]
0.835
0.539829432045001
              precision    recall  f1-score   support

           0       0.85      0.93      0.89       167
           1       0.29      0.15      0.20        33

    accuracy                           0.80       200
   macro avg       0.57      0.54      0.54       200
weighted avg       0.76      0.80      0.77       200

[[155  12]
 [ 28   5]]
0.8


C:\Users\Aditya\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


0.5428234440210489
              precision    recall  f1-score   support

           0       0.85      0.93      0.89       167
           1       0.31      0.15      0.20        33

    accuracy                           0.81       200
   macro avg       0.58      0.54      0.55       200
weighted avg       0.76      0.81      0.78       200

[[156  11]
 [ 28   5]]
0.805


C:\Users\Aditya\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Aditya\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


0.5185084376701142
              precision    recall  f1-score   support

           0       0.84      0.95      0.89       167
           1       0.25      0.09      0.13        33

    accuracy                           0.81       200
   macro avg       0.55      0.52      0.51       200
weighted avg       0.74      0.81      0.77       200

[[158   9]
 [ 30   3]]
0.805
0.5033569225185991
              precision    recall  f1-score   support

           0       0.84      0.95      0.89       167
           1       0.18      0.06      0.09        33

    accuracy                           0.80       200
   macro avg       0.51      0.50      0.49       200
weighted avg       0.73      0.80      0.76       200

[[158   9]
 [ 31   2]]
0.8


C:\Users\Aditya\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Aditya\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


0.515695880965342
              precision    recall  f1-score   support

           0       0.84      0.91      0.87       167
           1       0.21      0.12      0.15        33

    accuracy                           0.78       200
   macro avg       0.53      0.52      0.51       200
weighted avg       0.74      0.78      0.75       200

[[152  15]
 [ 29   4]]
0.78
0.527490473598258
              precision    recall  f1-score   support

           0       0.84      0.96      0.90       167
           1       0.33      0.09      0.14        33

    accuracy                           0.82       200
   macro avg       0.59      0.53      0.52       200
weighted avg       0.76      0.82      0.77       200

[[161   6]
 [ 30   3]]
0.82


C:\Users\Aditya\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Aditya\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


0.5304844855743058
              precision    recall  f1-score   support

           0       0.84      0.97      0.90       167
           1       0.38      0.09      0.15        33

    accuracy                           0.82       200
   macro avg       0.61      0.53      0.52       200
weighted avg       0.77      0.82      0.78       200

[[162   5]
 [ 30   3]]
0.825
0.536835420068953
              precision    recall  f1-score   support

           0       0.85      0.92      0.88       167
           1       0.28      0.15      0.20        33

    accuracy                           0.80       200
   macro avg       0.56      0.54      0.54       200
weighted avg       0.75      0.80      0.77       200

[[154  13]
 [ 28   5]]
0.795
0.5336599528216294
              precision    recall  f1-score   support

           0       0.84      0.95      0.89       167
           1       0.31      0.12      0.17        33

    accuracy                           0.81       200
   macro avg  

C:\Users\Aditya\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Aditya\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


In [143]:

# HOW WE FOUND OUR MODEL
# We calculated accuracy for all the values of k (k is the number of features that we select to form the model). And for
# selecting most promising features we use score functions, mutual_info_regression and f_regression. Also we tested our model
# with two algorithms, SVM and Random forest classifier. So in total we had 2*2*21 cases, all of the cases where calculated
# for accuracy and the model with highest F1 score had its result calculated and submitted on kaggle.
# We are writing this because we don't quite remember which setting gave our final score on Kaggle.

In [144]:
predictions #test predictions

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0], dtype=int64)

In [145]:
test_data= pd.read_csv(r'D:\cassandra\user_data_testing.csv')

In [146]:
test_data.head()

id  Alpha    Beta  Gamma   Delta  Epsilon  Zeta  Eta  Theta  Iota  \
0  1484353935   2615  1214.0      3   56000        2    15    5    101     5   
1  1490969236   2092     NaN      2  100000        2     8    9     99     5   
2  1487077817   3661  1223.0      3   78000        2    11   -1     75     5   
3  1485622755   2615  1214.0      3   68000        2    15    5     92     3   
4  1486796599   3661     NaN      2   63000        2    11    5     84     5   

    Kappa      Lambda   omikron  
0   60064  192.163993  0.029703  
1   71003  199.974998  0.020202  
2  450007  173.205081  0.040000  
3  550044  173.205081  0.032609  
4   60019  158.113883  0.023810

In [147]:
#mean_value=test_data['Beta'].mean() #calculate mean of Beta column
test_data['Beta'].fillna(value=test_data['Beta'].mean(), inplace=True)

In [148]:
test_data.head()

id  Alpha         Beta  Gamma   Delta  Epsilon  Zeta  Eta  Theta  \
0  1484353935   2615  1214.000000      3   56000        2    15    5    101   
1  1490969236   2092  1282.961972      2  100000        2     8    9     99   
2  1487077817   3661  1223.000000      3   78000        2    11   -1     75   
3  1485622755   2615  1214.000000      3   68000        2    15    5     92   
4  1486796599   3661  1282.961972      2   63000        2    11    5     84   

   Iota   Kappa      Lambda   omikron  
0     5   60064  192.163993  0.029703  
1     5   71003  199.974998  0.020202  
2     5  450007  173.205081  0.040000  
3     3  550044  173.205081  0.032609  
4     5   60019  158.113883  0.023810

In [149]:
x_test = pd.merge(grouped, test_data, on='id', how='inner') #merge both data to form testing dataset
x_test.head()

C:\Users\Aditya\Anaconda3\lib\site-packages\pandas\core\reshape\merge.py:617: UserWarning: merging between different levels can give an unintended result (2 levels on the left, 1 on the right)
  warnings.warn(msg, UserWarning)


id  (Late_2, average)  (Late_1, average)  (Late_3, average)  \
0      1           0.214286           0.142857           2.714286   
1  12615           0.272727           0.000000           0.000000   
2  40811           0.000000           0.000000           0.000000   
3  65668           0.000000           0.000000           0.000000   
4  72717           0.600000           0.200000           0.000000   

   (days_late_Sum, average)  (normal_payment, average)  (p_code, average)  \
0               2291.285714                  15.928571           8.785714   
1                  1.090909                  22.363636           6.090909   
2                  0.000000                  17.000000           9.000000   
3                  0.000000                  14.000000          10.000000   
4                 33.000000                  21.100000          10.500000   

   (last_update, average)  (curr_remaining, average)  (max_bal, average)  ...  \
0            38835.714286               53049.085714       246583.714286  ...   
1            40981.818182              117455.127273       238270.000000  ...   
2            41300.000000               39890.400000        78500.000000  ...   
3            41875.000000                1261.200000        12787.750000  ...   
4            40820.000000              410060.400000       671850.000000  ...   

   Gamma    Delta  Epsilon  Zeta  Eta  Theta  Iota   Kappa      Lambda  \
0      2  1000000        2     4   -1    100     5  650018    1.000000   
1      1   286000        2     3   -1     80     3  361003    1.000000   
2      3    70000        2    15    5    113     5   60033  167.122709   
3      3   120000        1    15    5    110     5   72000  187.082869   
4      3    30000        2    15    5    110     5   60005    1.000000   

    omikron  
0  0.020000  
1  0.012500  
2  0.026549  
3  0.027273  
4  0.027273  

[5 rows x 22 columns]

In [150]:
x_test_copy=x_test.copy()
x_test.drop('id',axis=1,inplace=True)
x_test.head()

(Late_2, average)  (Late_1, average)  (Late_3, average)  \
0           0.214286           0.142857           2.714286   
1           0.272727           0.000000           0.000000   
2           0.000000           0.000000           0.000000   
3           0.000000           0.000000           0.000000   
4           0.600000           0.200000           0.000000   

   (days_late_Sum, average)  (normal_payment, average)  (p_code, average)  \
0               2291.285714                  15.928571           8.785714   
1                  1.090909                  22.363636           6.090909   
2                  0.000000                  17.000000           9.000000   
3                  0.000000                  14.000000          10.000000   
4                 33.000000                  21.100000          10.500000   

   (last_update, average)  (curr_remaining, average)  (max_bal, average)  \
0            38835.714286               53049.085714       246583.714286   
1            40981.818182              117455.127273       238270.000000   
2            41300.000000               39890.400000        78500.000000   
3            41875.000000                1261.200000        12787.750000   
4            40820.000000              410060.400000       671850.000000   

   Alpha  ...  Gamma    Delta  Epsilon  Zeta  Eta  Theta  Iota   Kappa  \
0    523  ...      2  1000000        2     4   -1    100     5  650018   
1   1046  ...      1   286000        2     3   -1     80     3  361003   
2   2615  ...      3    70000        2    15    5    113     5   60033   
3   2615  ...      3   120000        1    15    5    110     5   72000   
4   2615  ...      3    30000        2    15    5    110     5   60005   

       Lambda   omikron  
0    1.000000  0.020000  
1    1.000000  0.012500  
2  167.122709  0.026549  
3  187.082869  0.027273  
4    1.000000  0.027273  

[5 rows x 21 columns]

In [151]:
x_test=normalize(x_test)
x_test.shape

(410, 21)

In [152]:
x_test_fs = fs.transform(x_test)
x_test_fs.shape

(410, 21)

In [153]:
submission = logmodel.predict(x_test_fs)

In [154]:
submission

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [155]:
x_test_copy.shape

(410, 22)

In [156]:
x_test_copy.head()

id  (Late_2, average)  (Late_1, average)  (Late_3, average)  \
0      1           0.214286           0.142857           2.714286   
1  12615           0.272727           0.000000           0.000000   
2  40811           0.000000           0.000000           0.000000   
3  65668           0.000000           0.000000           0.000000   
4  72717           0.600000           0.200000           0.000000   

   (days_late_Sum, average)  (normal_payment, average)  (p_code, average)  \
0               2291.285714                  15.928571           8.785714   
1                  1.090909                  22.363636           6.090909   
2                  0.000000                  17.000000           9.000000   
3                  0.000000                  14.000000          10.000000   
4                 33.000000                  21.100000          10.500000   

   (last_update, average)  (curr_remaining, average)  (max_bal, average)  ...  \
0            38835.714286               53049.085714       246583.714286  ...   
1            40981.818182              117455.127273       238270.000000  ...   
2            41300.000000               39890.400000        78500.000000  ...   
3            41875.000000                1261.200000        12787.750000  ...   
4            40820.000000              410060.400000       671850.000000  ...   

   Gamma    Delta  Epsilon  Zeta  Eta  Theta  Iota   Kappa      Lambda  \
0      2  1000000        2     4   -1    100     5  650018    1.000000   
1      1   286000        2     3   -1     80     3  361003    1.000000   
2      3    70000        2    15    5    113     5   60033  167.122709   
3      3   120000        1    15    5    110     5   72000  187.082869   
4      3    30000        2    15    5    110     5   60005    1.000000   

    omikron  
0  0.020000  
1  0.012500  
2  0.026549  
3  0.027273  
4  0.027273  

[5 rows x 22 columns]

In [157]:
#submission = np.append(submission, x_test_copy['id'], axis=1)
sol = {'label':submission,
       'id':x_test_copy['id'] }

In [158]:
sol = pd.DataFrame(sol)

In [159]:
sol.head(10)

label      id
0      0       1
1      0   12615
2      0   40811
3      0   65668
4      0   72717
5      0  201825
6      0  208874
7      0  239296
8      0  254507
9      0  274912

In [160]:
sol.to_csv(r'D:\cassandra\answers.csv', index=False)